logging:
  level:
    in.hocg: debug

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mysql.localhost:3306/db_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: hocgin
    schema:
      - classpath:db/schema-maria.sql
    data:
      - classpath:db/data-maria.sql
    initialization-mode: ALWAYS
  wolves:
    slave:
      - name: n1
        url: jdbc:mariadb://mysql.localhost:3306/db_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        driver-class-name: org.mariadb.jdbc.Driver
        username: root
        password: hocgin
      - name: n2
        url: jdbc:mariadb://mysql.localhost:3306/db_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        driver-class-name: org.mariadb.jdbc.Driver
        username: root
        password: hocgin
    helper-class: in.hocg.wolves.spring.boot.autoconfigure.pool.DefaultDataSourceHelper
mybatis:
  mapper-locations: classpath:mapper/*.xml

